// <auto-generated />
using System;
using Binsoft.CRSDdashboard.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Binsoft.CRSDdashboard.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260225105752_ChangedSeederValues")]
    partial class ChangedSeederValues
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("Binsoft.CRSDdashboard.Api.Models.Entities.Ecopart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<double?>("Height")
                        .HasColumnType("REAL");

                    b.Property<double>("Length")
                        .HasColumnType("REAL");

                    b.Property<int>("MaterialId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<double?>("Radius")
                        .HasColumnType("REAL");

                    b.Property<int>("ShapeType")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Width")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId");

                    b.ToTable("Ecoparts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Height = 5.0,
                            Length = 3.0,
                            MaterialId = 1,
                            Name = "PET Plate",
                            ShapeType = 1,
                            Width = 2.0
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Height = 5.0,
                            Length = 1.0,
                            MaterialId = 2,
                            Name = "HDPE Plate",
                            ShapeType = 1,
                            Width = 0.5
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Height = 5.0,
                            Length = 4.0,
                            MaterialId = 3,
                            Name = "LDPE Plate",
                            ShapeType = 1,
                            Width = 6.0
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Height = 5.0,
                            Length = 0.10000000000000001,
                            MaterialId = 4,
                            Name = "PP Plate",
                            ShapeType = 1,
                            Width = 0.5
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2024, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Height = 5.0,
                            Length = 3.0,
                            MaterialId = 5,
                            Name = "PS Plate",
                            ShapeType = 1,
                            Width = 2.0
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2024, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Height = 5.0,
                            Length = 10.0,
                            MaterialId = 6,
                            Name = "PVC Plate",
                            ShapeType = 1,
                            Width = 20.0
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2024, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Height = 5.0,
                            Length = 1.0,
                            MaterialId = 7,
                            Name = "PLA Plate",
                            ShapeType = 1,
                            Width = 1.0
                        });
                });

            modelBuilder.Entity("Binsoft.CRSDdashboard.Api.Models.Entities.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Co2PerKg")
                        .HasColumnType("REAL");

                    b.Property<double>("Density")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Material");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Co2PerKg = 2.25,
                            Density = 1.27,
                            Name = "PET"
                        },
                        new
                        {
                            Id = 2,
                            Co2PerKg = 3.0899999999999999,
                            Density = 0.95999999999999996,
                            Name = "HDPE"
                        },
                        new
                        {
                            Id = 3,
                            Co2PerKg = 3.0899999999999999,
                            Density = 0.93999999999999995,
                            Name = "LDPE"
                        },
                        new
                        {
                            Id = 4,
                            Co2PerKg = 3.0899999999999999,
                            Density = 0.91000000000000003,
                            Name = "PP"
                        },
                        new
                        {
                            Id = 5,
                            Co2PerKg = 3.3300000000000001,
                            Density = 1.0600000000000001,
                            Name = "PS"
                        },
                        new
                        {
                            Id = 6,
                            Co2PerKg = 1.3899999999999999,
                            Density = 1.45,
                            Name = "PVC"
                        },
                        new
                        {
                            Id = 7,
                            Co2PerKg = 0.010999999999999999,
                            Density = 1.24,
                            Name = "PLA"
                        });
                });

            modelBuilder.Entity("Binsoft.CRSDdashboard.Api.Models.Entities.Ecopart", b =>
                {
                    b.HasOne("Binsoft.CRSDdashboard.Api.Models.Entities.Material", "Material")
                        .WithMany("Ecoparts")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");
                });

            modelBuilder.Entity("Binsoft.CRSDdashboard.Api.Models.Entities.Material", b =>
                {
                    b.Navigation("Ecoparts");
                });
#pragma warning restore 612, 618
        }
    }
}
