// <auto-generated />
using System;
using Binsoft.CRSDdashboard.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Binsoft.CRSDdashboard.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("Binsoft.CRSDdashboard.Api.Models.Entities.Ecopart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<double>("Height")
                        .HasColumnType("REAL");

                    b.Property<double>("Length")
                        .HasColumnType("REAL");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<double>("Weight")
                        .HasColumnType("REAL");

                    b.Property<double>("Width")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Ecoparts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Height = 5.0,
                            Length = 300.0,
                            Material = "PET",
                            Name = "PET Plate",
                            Weight = 1.2,
                            Width = 200.0
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Height = 5.0,
                            Length = 300.0,
                            Material = "HDPE",
                            Name = "HDPE Plate",
                            Weight = 1.5,
                            Width = 200.0
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Height = 5.0,
                            Length = 300.0,
                            Material = "LDPE",
                            Name = "LDPE Plate",
                            Weight = 1.3999999999999999,
                            Width = 200.0
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Height = 5.0,
                            Length = 300.0,
                            Material = "PP",
                            Name = "PP Plate",
                            Weight = 1.3,
                            Width = 200.0
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2024, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Height = 5.0,
                            Length = 300.0,
                            Material = "PS",
                            Name = "PS Plate",
                            Weight = 1.6000000000000001,
                            Width = 200.0
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2024, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Height = 5.0,
                            Length = 300.0,
                            Material = "PVC",
                            Name = "PVC Plate",
                            Weight = 2.1000000000000001,
                            Width = 200.0
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2024, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Height = 5.0,
                            Length = 300.0,
                            Material = "PLA",
                            Name = "PLA Plate",
                            Weight = 1.8,
                            Width = 200.0
                        });
                });

            modelBuilder.Entity("Binsoft.CRSDdashboard.Api.Models.Entities.EmissionFactor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Co2PerKg")
                        .HasColumnType("REAL");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Material")
                        .IsUnique();

                    b.ToTable("EmissionFactors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Co2PerKg = 2.25,
                            Material = "PET"
                        },
                        new
                        {
                            Id = 2,
                            Co2PerKg = 3.0899999999999999,
                            Material = "HDPE"
                        },
                        new
                        {
                            Id = 3,
                            Co2PerKg = 3.0899999999999999,
                            Material = "LDPE"
                        },
                        new
                        {
                            Id = 4,
                            Co2PerKg = 3.0899999999999999,
                            Material = "PP"
                        },
                        new
                        {
                            Id = 5,
                            Co2PerKg = 3.3300000000000001,
                            Material = "PS"
                        },
                        new
                        {
                            Id = 6,
                            Co2PerKg = 1.3899999999999999,
                            Material = "PVC"
                        },
                        new
                        {
                            Id = 7,
                            Co2PerKg = 0.010999999999999999,
                            Material = "PLA"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
