// <auto-generated />
using System;
using Binsoft.Ecoparts.Infrastructure.Persistances;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Binsoft.Ecoparts.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260303121149_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("Binsoft.Ecoparts.Domain.Entities.Ecopart", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MaterialId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ShapeId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Ecoparts");
                });

            modelBuilder.Entity("Binsoft.Ecoparts.Domain.Entities.Material", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<double>("Density")
                        .HasColumnType("REAL");

                    b.Property<double>("EmissionFactor")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Materials", (string)null);
                });

            modelBuilder.Entity("Binsoft.Ecoparts.Domain.Entities.Shape", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ShapeType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Shapes", (string)null);
                });

            modelBuilder.Entity("Binsoft.Ecoparts.Domain.Entities.Ecopart", b =>
                {
                    b.OwnsOne("Binsoft.Ecoparts.Domain.ValueObjects.Dimension", "Dimension", b1 =>
                        {
                            b1.Property<Guid>("EcopartId")
                                .HasColumnType("TEXT");

                            b1.Property<double>("Height")
                                .HasColumnType("REAL")
                                .HasColumnName("DimHeight");

                            b1.Property<double?>("Length")
                                .HasColumnType("REAL")
                                .HasColumnName("DimLength");

                            b1.Property<double?>("Radius")
                                .HasColumnType("REAL")
                                .HasColumnName("DimRadius");

                            b1.Property<double?>("Width")
                                .HasColumnType("REAL")
                                .HasColumnName("DimWidth");

                            b1.HasKey("EcopartId");

                            b1.ToTable("Ecoparts");

                            b1.WithOwner()
                                .HasForeignKey("EcopartId");
                        });

                    b.Navigation("Dimension")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
